<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ER1I82SI" failures="1" tests="2" name="Test" time="8.424" errors="0" timestamp="2023-07-27T21:50:25 IST">
  <testcase classname="testsuites.TestNewOpp" name="excelread" time="0.785"/>
  <testcase classname="testsuites.TestNewOpp" name="title" time="0.351">
    <failure type="java.lang.AssertionError" message="expected [Login | Salesforce] but found [Lightning Experience]">
      <![CDATA[java.lang.AssertionError: expected [Login | Salesforce] but found [Lightning Experience]
at testsuites.TestNewOpp.title(TestNewOpp.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- title -->
</testsuite> <!-- Test -->
